// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://perasuksapjsgebmxvso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcmFzdWtzYXBqc2dlYm14dnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODcwNTIsImV4cCI6MjA1NzM2MzA1Mn0.WwnhiMFTxtgvBuowaLW2AQZVlzf_FK7-Jfr-K7-gkSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);